name: Consumer Pact Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'consumer/**'
      - '.github/workflows/pact-consumer.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'consumer/**'

jobs:
  consumer-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run consumer tests
        run: npm run test:consumer
      
      - name: Publish Pact contract
        env:
          PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_URL }}
          PACT_BROKER_USERNAME: ${{ secrets.PACT_BROKER_USERNAME }}
          PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}
        run: |
          # Create version based on git information
          GIT_COMMIT=$(git rev-parse HEAD)
          GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          
          # Install pact CLI
          docker pull pactfoundation/pact-cli:latest
          
          # Publish pacts
          docker run --rm \
            -v ${PWD}:${PWD} \
            -w ${PWD} \
            -e PACT_BROKER_BASE_URL \
            -e PACT_BROKER_USERNAME \
            -e PACT_BROKER_PASSWORD \
            pactfoundation/pact-cli:latest \
            broker publish ${PWD}/pacts \
            --consumer-app-version ${GIT_COMMIT} \
            --branch ${GITHUB_REF_NAME} \
            --tag ${GITHUB_REF_NAME}
      
      - name: Can I Deploy?
        env:
          PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_URL }}
          PACT_BROKER_USERNAME: ${{ secrets.PACT_BROKER_USERNAME }}
          PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}
        run: |
          GIT_COMMIT=$(git rev-parse HEAD)
          
          # Check if it's safe to deploy
          docker run --rm \
            -e PACT_BROKER_BASE_URL \
            -e PACT_BROKER_USERNAME \
            -e PACT_BROKER_PASSWORD \
            pactfoundation/pact-cli:latest \
            broker can-i-deploy \
            --pacticipant GettingStartedOrderWeb \
            --version ${GIT_COMMIT} \
            --to production
